# Generated by Django 3.2.3 on 2021-05-20 02:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('userpassword', models.CharField(max_length=20)),
            ],
            managers=[
                ('userob', django.db.models.manager.Manager()),
            ],
        ),
    ]
